; ; [pytest]
; ; addopts = -v
; ; testpaths = tests

; [pytest]
; addopts = -v
; testpaths = tests
; markers =
;     smoke: critical tests
;     regression: full suite

[pytest]
markers =
    smoke: critical tests
    regression: full suite